### ISSUE TITLE
ascendancy nodes for infernalist (no info on node location)

### ISSUE THREAD

**Issue by shawnkfox** [marcoaaguiar/poe2-tree#138]
![infer10](https://github.com/user-attachments/assets/1815cf7c-9fa6-472f-82cd-af4f07b460e8)
![infer9](https://github.com/user-attachments/assets/5ac4aed9-f026-4b0e-8dff-1f5000bf7fe9)
![infer8](https://github.com/user-attachments/assets/82297fcb-3f32-44a5-a020-1e25d0336468)
![infer7](https://github.com/user-attachments/assets/adeed754-6d09-4981-a777-3fccea1019e3)
![infer6](https://github.com/user-attachments/assets/a04eaece-d8f4-4943-8db4-5b02c31b4df9)
![infer5](https://github.com/user-attachments/assets/25bb7bb3-7845-4493-8f3b-701cb430a981)
![infer4](https://github.com/user-attachments/assets/f59c5b81-bc27-4bf1-aa29-4cd80ff34bd2)
![infer3](https://github.com/user-attachments/assets/c06a9bcb-4d7e-4c8f-b62f-9d056263747c)
![infer2](https://github.com/user-attachments/assets/c0c95877-c98f-48cb-ac22-f5c6828f0e68)
![infer1](https://github.com/user-attachments/assets/500c2edb-c16a-4f85-b3a2-93eda07e977b)

**Comment by Alexis-Pannetier** [comment]
What is the source ?
I can't see which is which one

**Comment by shawnkfox** [comment]
It was just an imgr link, no info was given on location of the nodes unfortunately.  If I get more info I'll update.

**Comment by lfmnovaes** [comment]
found this: https://imgur.com/a/Tikno9x
the problem is, 11 notables

**Comment by Alexis-Pannetier** [comment]
Ascend added by predictive way 👍

**Comment by lfmnovaes** [comment]
Completed the Infernalist nodes with the information we gathered here #140 , can you double-check there too? @Alexis-Pannetier 
I did not rely on the numbers from one of the imgur images

**Comment by Alexis-Pannetier** [comment]
Skill tree version is different,
IDK about adding "Seething Body" node

I think you can rebase and check the changes

**Comment by lfmnovaes** [comment]
@Alexis-Pannetier Why not add the Seething Body?
I saw it, and I know it is weird that it's the only ascendancy with 11 notables, but that's the best thing we had. Added the rest of the information based on tooltip localization.

**Comment by shawnkfox** [comment]
GGG is going to release all of the ascendancies due to leaks, I'd hold off on it and just fix it to correct version when they do.

**Comment by marcoaaguiar** [comment]
@shawnkfox did they say anything about this?
