### ISSUE TITLE
Official Ascendancy reveal

### ISSUE THREAD

**Issue by Alexis-Pannetier** [marcoaaguiar/poe2-tree#156]
https://www.pathofexile.com/forum/view-thread/3592012

![image](https://github.com/user-attachments/assets/ddde022e-ab55-40ec-aeb6-d0de3cda58d0)
![image](https://github.com/user-attachments/assets/f4098e68-78f6-4820-8d74-9b1740c70358)

![image](https://github.com/user-attachments/assets/6e974be0-dd78-44cc-9016-512737eadcbe)
![image](https://github.com/user-attachments/assets/d1f6d7c5-d7a8-4859-9874-25d9a74247d1)

![image](https://github.com/user-attachments/assets/930e19cc-a983-47af-9300-5f2ef1fff62b)
![image](https://github.com/user-attachments/assets/260d7b6f-209f-48ee-8c21-43a566ff1aa4)

![image](https://github.com/user-attachments/assets/dc109af7-2a7d-4210-9af9-6d491f1fb11e)
![image](https://github.com/user-attachments/assets/df955981-e8e6-45a8-8a22-0f93c4460376)

![image](https://github.com/user-attachments/assets/fb07df98-dca4-4dfa-92dc-a4642ea3cac0)
![image](https://github.com/user-attachments/assets/2e7b1383-ee73-4aa9-aa2a-42d5d3a84fb8)

![image](https://github.com/user-attachments/assets/6c5507b7-2f90-4a12-bb87-fc3e852f1c02)
![image](https://github.com/user-attachments/assets/ac1b960a-ff66-414a-b85c-358315b42730)

**Comment by marcoaaguiar** [comment]
Can this closed now?
