### ISSUE TITLE
404 when loading a saved build

### ISSUE THREAD

**Issue by lfmnovaes** [marcoaaguiar/poe2-tree#175]
When trying to load the production recent implementation (save/load builds), gives a 404. Probably need to use the `base` variable to construct the URL when loading, because tries to redirect without the `/poe2-tree` in the URL 

@marcoaaguiar @danielbruni 

![image](https://github.com/user-attachments/assets/6b7bf842-b4ab-47c6-a502-335899bc1060)

**Comment by danielbruni** [comment]
Added a PR #176

**Comment by lfmnovaes** [comment]
It seems the issue is gone
