### ISSUE TITLE
stitch (missing) outer dex tree from tgs onto gamescom tree

### ISSUE THREAD

**Issue by meatwallace** [marcoaaguiar/poe2-tree#19]
there's a few nodes there that have been revealed but couldn't be annotated because they're missing from the gamescom tree.

i'll do this later if no one else looks at it first.

source:

- [tree images](https://poe2db.tw/us/Passive_Skill_Tree)
- [dex/int nodes from dreamcore](https://www.youtube.com/watch?v=aTi9fF6fU24)

**Comment by shawnkfox** [comment]
I already took care of it and uploaded the image

**Comment by meatwallace** [comment]
> I already took care of it and uploaded the image

just for reference: 
- @shawnkfox's original PR with updated image - https://github.com/marcoaaguiar/poe2-tree/pull/20
- @neo-daru's alternative PR with other work - https://github.com/marcoaaguiar/poe2-tree/pull/46

once either of these are merged, additional nodes can be added to the data set and data pulled from dreamcore's vid in a follow up PR.

**Comment by marcoaaguiar** [comment]
I've merged #20  this issue is not blocked anymore.

**Comment by meatwallace** [comment]
looks like someone added the nodes :) will close.
