### ISSUE TITLE
Nodes in a linkedlist

### ISSUE THREAD

**Issue by buzzdead** [marcoaaguiar/poe2-tree#40]
Would be nice if nodes were added with a head and a tail, could just reverse it in an algorithm going the other way.

If that was in place then one could select a starting place, and see how many points needed to go to a specific node from there (shortest path), and select for a different path.

**Comment by marcoaaguiar** [comment]
The passive tree is a grapu, I'm not sure how to use linked lists to model that. But I can totally see the value of knowing which nodes are connected to a node

**Comment by buzzdead** [comment]
I tried with some kind of proximity around the node to find the previous node and the next node, it wasn't feasible to say the least. Only solution is to manually do it, sadly.

**Comment by marcoaaguiar** [comment]
Maybe using opencv it would be possible to identify the connection between the nodes.
The tree-scanner folder contains the code for iding the nodes with opencv if you want to try something that's a good start
