### ISSUE TITLE
Can anybody help me add these DEX/INT nodes from my play test at Tokyo Game Show?

### ISSUE THREAD

**Issue by thirajade** [marcoaaguiar/poe2-tree#45]
Moment of Truth
![image](https://github.com/user-attachments/assets/97ff48e5-9ebe-468b-86e9-ba00dc00a8ab)

Mystic Stance
![image](https://github.com/user-attachments/assets/2f9f662e-2632-40b3-8524-07a5a6df2c02)

Essence of the Mountain
![image](https://github.com/user-attachments/assets/0d22fec1-cac1-40ff-839d-4982c2442db6)

Finesse
![image](https://github.com/user-attachments/assets/14135dcc-abc1-4f53-b1aa-55bc2404c4bf)

Harmonic Generator
![image](https://github.com/user-attachments/assets/4629d93c-9a0c-44bb-a378-f47604e19d48)

Immaterial
![image](https://github.com/user-attachments/assets/a286eaf0-6d22-465e-8446-c82d91b8abbe)

Shimmering
![image](https://github.com/user-attachments/assets/9dcfe7ec-6f53-4616-a73a-8e171a0ba4d5)

Siphon
![image](https://github.com/user-attachments/assets/a29c0fb8-8136-49f2-af48-77a9fbada35f)

Lust for Power
![image](https://github.com/user-attachments/assets/44e0a039-d010-4879-96b7-dee364e00d20)

**Comment by marcoaaguiar** [comment]
I believe this can be closed now, thanks for submitting!
