### ISSUE TITLE
Move contribution information to CONTRIBUTE.md

### ISSUE THREAD

**Issue by Kehrweek** [marcoaaguiar/poe2-tree#55]
The contribution guidelines should be moved to a separate CONTRIBUTE.md file.

**Comment by marcoaaguiar** [comment]
We got two PR #115 and #164 regarding this subject

I'm with @meatwallace on this (https://github.com/marcoaaguiar/poe2-tree/pull/115#issuecomment-2513066357)
> i'd suggest the contribution notes are left in the main README.
> 
> for any other normal dev project, splitting it out is fine, but there's been a lot of contributors that have limited technical/development backgrounds from what i've observed and having a seperate doc means it's less intuitive for those types of folks to get started. just my 2c though

I don't see a positive side on removing the contribute from the README. Effectively, the core of the README is how to contribute. 
If this was a library I would make sense to have a README that focus on the end user and separated `.md` for contributors. 
The end user, in our case are the people accessing the main site, those that arrive in the repository are already interested in contributing, again I don't see the advantage of hiding instructions in another link.

**Comment by josephjaniga** [comment]
> I don't see a positive side on removing the contribute from the README.

I think that's reasonable, and sorry I am not trying to make more work - I've closed out #164 .  I would strongly suggest this issue and the other PR #115 be closed to avoid further confusion.

I only ended up here doing what I thought was being asked.
