### ISSUE TITLE
Further development using libraries

### ISSUE THREAD

**Issue by Kehrweek** [marcoaaguiar/poe2-tree#82]
As the tool is getting bigger and bigger, we should consider using libraries for some things like ui elements and fundamental features.

For example [TailwindCss](https://tailwindcss.com) for preconfigured classes and fast styling.

**Comment by neo-daru** [comment]
not sure what @marcoaaguiar wants to do, but yeah it's probably better to make components, use tailwind and some other libs, especially if you're planning to keep adding more features and functionality passed PoE2 early access launch

**Comment by marcoaaguiar** [comment]
Tailwind added :)
