### ISSUE TITLE
Additional source witch start area

### ISSUE THREAD

**Issue by lmripod** [marcoaaguiar/poe2-tree#90]
Legendary Drops https://www.youtube.com/watch?v=l_OXzSCHVzI

@5:40 shows node S709 Spell Damage "10% increased Spell Damage"
@5:41 shows node between S693 and S709: Mana Regeneration "10% increased Mana Regeneration Rate" which could be added with current entry "Minions have 10% increased maximum life"
@5:42 shows node S692 Spell Damage "8% increased Spell Damage"

**Comment by Darxo** [comment]
Ill make a PR for that
